# SOPS configuration file
# This file defines which keys can decrypt which secrets

keys:
  # Rhys's GPG key
  - &rhys_gpg 9AE7021E741E85B918D27E4373DF06673FCE9371

creation_rules:
  # Rule for all secret files in this directory
  - path_regex: .*\.yaml$
    key_groups:
      - pgp:
          - *rhys_gpg

